# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'working_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(750, 650))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#transfer_tab{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #95afc7, stop: 1 #FFFFFF);\n"
"}\n"
"#renaming_tab{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #95afc7, stop: 1 #FFFFFF);\n"
"}\n"
"#reduction_tab{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #95afc7, stop: 1 #FFFFFF);\n"
"}\n"
"#eden_ap{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #95afc7, stop: 1 #FFFFFF);\n"
"}\n"
"#db_tab{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #95afc7, stop: 1 #FFFFFF);\n"
"}\n"
"QTextEdit{\n"
"font: 12pt \"Serif\";\n"
"border: 2px solid grey;\n"
"border-radius: 5px;\n"
"selection-background-color: darkgray;\n"
"background: lightblue;\n"
"color: rgb(40, 46, 58);\n"
"}\n"
"QLineEdit {\n"
"font: 10pt \"Serif\";\n"
"border: 1px solid grey;\n"
"border-radius: 4px;\n"
"selection-background-color: darkgray;\n"
"}\n"
"QPushButton {\n"
"    font: 12pt \"Serif\";\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: lightgray;\n"
"}\n"
"QGroupBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1.5ex; /* leave space at the top for the title */\n"
"    font: bold 12pt \"Serif\" ;  \n"
"}\n"
"\n"
"#db_connection{\n"
"   border: 0px ;\n"
"    border-radius: 0px;\n"
"    margin-top: 0ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"#db_query{\n"
"    border: 0px ;\n"
"    border-radius: 0px;\n"
"    margin-top: 0ex; /* leave space at the top for the title */\n"
"\n"
"}\n"
"#options_box_rname{\n"
" font: bold 11pt  \"Serif\"\n"
"}\n"
"QLabel#app_info_rnamelabel{\n"
" font: bold 10pt \"Serif\";\n"
"}\n"
"QLabel{\n"
"font: 12pt \"Serif\";\n"
"}\n"
"QLabel#top_label{\n"
"font: bold 12pt  \"Serif\"\n"
"}\n"
"QRadioButton{\n"
"font: 12pt \"Serif\";\n"
"text-align: center;\n"
"}\n"
"QCheckBox{\n"
"font: 12pt \"Serif\";\n"
"}\n"
"")
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWdgt = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWdgt.setGeometry(QtCore.QRect(0, 0, 750, 650))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWdgt.setFont(font)
        self.tabWdgt.setToolTip("")
        self.tabWdgt.setAccessibleName("")
        self.tabWdgt.setAutoFillBackground(True)
        self.tabWdgt.setTabBarAutoHide(False)
        self.tabWdgt.setObjectName("tabWdgt")
        self.transfer_tab = QtWidgets.QWidget()
        self.transfer_tab.setAutoFillBackground(False)
        self.transfer_tab.setStyleSheet("")
        self.transfer_tab.setObjectName("transfer_tab")
        self.transfer_info = QtWidgets.QGroupBox(self.transfer_tab)
        self.transfer_info.setGeometry(QtCore.QRect(20, 20, 710, 480))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.transfer_info.setFont(font)
        self.transfer_info.setAutoFillBackground(False)
        self.transfer_info.setObjectName("transfer_info")
        self.output = QtWidgets.QTextEdit(self.transfer_info)
        self.output.setGeometry(QtCore.QRect(50, 240, 601, 181))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.output.setFont(font)
        self.output.setStyleSheet("")
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.select_dir = QtWidgets.QPushButton(self.transfer_info)
        self.select_dir.setGeometry(QtCore.QRect(60, 60, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_dir.setFont(font)
        self.select_dir.setObjectName("select_dir")
        self.MS_dir = QtWidgets.QPushButton(self.transfer_info)
        self.MS_dir.setGeometry(QtCore.QRect(60, 140, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MS_dir.setFont(font)
        self.MS_dir.setObjectName("MS_dir")
        self.text_dir = QtWidgets.QLineEdit(self.transfer_info)
        self.text_dir.setGeometry(QtCore.QRect(70, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_dir.setFont(font)
        self.text_dir.setStyleSheet("")
        self.text_dir.setObjectName("text_dir")
        self.Ms_text = QtWidgets.QLineEdit(self.transfer_info)
        self.Ms_text.setGeometry(QtCore.QRect(70, 180, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Ms_text.setFont(font)
        self.Ms_text.setObjectName("Ms_text")
        self.ovr_transfer = QtWidgets.QPushButton(self.transfer_info)
        self.ovr_transfer.setGeometry(QtCore.QRect(430, 60, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ovr_transfer.setFont(font)
        self.ovr_transfer.setObjectName("ovr_transfer")
        self.ovr_text = QtWidgets.QLineEdit(self.transfer_info)
        self.ovr_text.setGeometry(QtCore.QRect(430, 110, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ovr_text.setFont(font)
        self.ovr_text.setStyleSheet("")
        self.ovr_text.setObjectName("ovr_text")
        self.quit_button = QtWidgets.QPushButton(self.transfer_tab)
        self.quit_button.setGeometry(QtCore.QRect(450, 550, 111, 41))
        self.quit_button.setObjectName("quit_button")
        self.strt_trnsf = QtWidgets.QPushButton(self.transfer_tab)
        self.strt_trnsf.setGeometry(QtCore.QRect(190, 550, 131, 41))
        self.strt_trnsf.setObjectName("strt_trnsf")
        self.tabWdgt.addTab(self.transfer_tab, "")
        self.renaming_tab = QtWidgets.QWidget()
        self.renaming_tab.setAccessibleName("")
        self.renaming_tab.setObjectName("renaming_tab")
        self.rname_box = QtWidgets.QGroupBox(self.renaming_tab)
        self.rname_box.setGeometry(QtCore.QRect(0, 60, 791, 601))
        self.rname_box.setObjectName("rname_box")
        self.table_rname = QtWidgets.QTableWidget(self.rname_box)
        self.table_rname.setGeometry(QtCore.QRect(325, 340, 420, 181))
        self.table_rname.setAlternatingRowColors(True)
        self.table_rname.setTextElideMode(QtCore.Qt.ElideLeft)
        self.table_rname.setRowCount(5)
        self.table_rname.setColumnCount(4)
        self.table_rname.setObjectName("table_rname")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_rname.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_rname.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_rname.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.table_rname.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_rname.setItem(4, 3, item)
        self.info_value_hrdset = QtWidgets.QLabel(self.rname_box)
        self.info_value_hrdset.setGeometry(QtCore.QRect(380, 270, 291, 51))
        self.info_value_hrdset.setObjectName("info_value_hrdset")
        self.hrd_src_dir = QtWidgets.QLineEdit(self.rname_box)
        self.hrd_src_dir.setGeometry(QtCore.QRect(390, 70, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.hrd_src_dir.setFont(font)
        self.hrd_src_dir.setObjectName("hrd_src_dir")
        self.app_info = QtWidgets.QTextEdit(self.rname_box)
        self.app_info.setGeometry(QtCore.QRect(10, 270, 291, 231))
        self.app_info.setReadOnly(True)
        self.app_info.setObjectName("app_info")
        self.modified_dir = QtWidgets.QLineEdit(self.rname_box)
        self.modified_dir.setGeometry(QtCore.QRect(390, 150, 281, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.modified_dir.setFont(font)
        self.modified_dir.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.modified_dir.setAutoFillBackground(False)
        self.modified_dir.setObjectName("modified_dir")
        self.rname_src = QtWidgets.QPushButton(self.rname_box)
        self.rname_src.setGeometry(QtCore.QRect(420, 30, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rname_src.setFont(font)
        self.rname_src.setObjectName("rname_src")
        self.rname_dest = QtWidgets.QPushButton(self.rname_box)
        self.rname_dest.setGeometry(QtCore.QRect(420, 110, 250, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rname_dest.setFont(font)
        self.rname_dest.setObjectName("rname_dest")
        self.strt_rnaming = QtWidgets.QPushButton(self.rname_box)
        self.strt_rnaming.setGeometry(QtCore.QRect(590, 200, 91, 41))
        self.strt_rnaming.setObjectName("strt_rnaming")
        self.options_box_rname = QtWidgets.QGroupBox(self.rname_box)
        self.options_box_rname.setGeometry(QtCore.QRect(20, 30, 221, 191))
        self.options_box_rname.setObjectName("options_box_rname")
        self.keep_orig_rname = QtWidgets.QCheckBox(self.options_box_rname)
        self.keep_orig_rname.setGeometry(QtCore.QRect(10, 100, 171, 23))
        self.keep_orig_rname.setObjectName("keep_orig_rname")
        self.recursive_rname = QtWidgets.QCheckBox(self.options_box_rname)
        self.recursive_rname.setGeometry(QtCore.QRect(10, 30, 201, 23))
        self.recursive_rname.setObjectName("recursive_rname")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.options_box_rname)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 60, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.hrd_chng_type = QtWidgets.QRadioButton(self.renaming_tab)
        self.hrd_chng_type.setGeometry(QtCore.QRect(200, 30, 171, 23))
        self.hrd_chng_type.setChecked(True)
        self.hrd_chng_type.setObjectName("hrd_chng_type")
        self.rname_type = QtWidgets.QRadioButton(self.renaming_tab)
        self.rname_type.setGeometry(QtCore.QRect(450, 30, 112, 23))
        self.rname_type.setObjectName("rname_type")
        self.top_label = QtWidgets.QLabel(self.renaming_tab)
        self.top_label.setGeometry(QtCore.QRect(230, 0, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.top_label.setFont(font)
        self.top_label.setObjectName("top_label")
        self.app_info_rnamelabel = QtWidgets.QLabel(self.renaming_tab)
        self.app_info_rnamelabel.setGeometry(QtCore.QRect(60, 300, 171, 17))
        self.app_info_rnamelabel.setObjectName("app_info_rnamelabel")
        self.tabWdgt.addTab(self.renaming_tab, "")
        self.reduction_tab = QtWidgets.QWidget()
        self.reduction_tab.setObjectName("reduction_tab")
        self.input_files_reduction = QtWidgets.QGroupBox(self.reduction_tab)
        self.input_files_reduction.setGeometry(QtCore.QRect(20, 10, 711, 261))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_files_reduction.setFont(font)
        self.input_files_reduction.setObjectName("input_files_reduction")
        self.select_objs_reduction = QtWidgets.QPushButton(self.input_files_reduction)
        self.select_objs_reduction.setGeometry(QtCore.QRect(290, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_objs_reduction.setFont(font)
        self.select_objs_reduction.setObjectName("select_objs_reduction")
        self.select_cal_reduction = QtWidgets.QPushButton(self.input_files_reduction)
        self.select_cal_reduction.setGeometry(QtCore.QRect(290, 100, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_cal_reduction.setFont(font)
        self.select_cal_reduction.setObjectName("select_cal_reduction")
        self.cal_comp = QtWidgets.QLineEdit(self.input_files_reduction)
        self.cal_comp.setGeometry(QtCore.QRect(330, 150, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cal_comp.setFont(font)
        self.cal_comp.setText("")
        self.cal_comp.setObjectName("cal_comp")
        self.recycle_cal = QtWidgets.QCheckBox(self.input_files_reduction)
        self.recycle_cal.setGeometry(QtCore.QRect(430, 190, 175, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.recycle_cal.setFont(font)
        self.recycle_cal.setChecked(True)
        self.recycle_cal.setObjectName("recycle_cal")
        self.twilight_flats = QtWidgets.QCheckBox(self.input_files_reduction)
        self.twilight_flats.setGeometry(QtCore.QRect(280, 190, 161, 35))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.twilight_flats.setFont(font)
        self.twilight_flats.setObjectName("twilight_flats")
        self.nprocess = QtWidgets.QSpinBox(self.input_files_reduction)
        self.nprocess.setGeometry(QtCore.QRect(587, 100, 71, 24))
        self.nprocess.setWrapping(True)
        self.nprocess.setMinimum(3)
        self.nprocess.setMaximum(12)
        self.nprocess.setObjectName("nprocess")
        self.nprocess_label = QtWidgets.QLabel(self.input_files_reduction)
        self.nprocess_label.setGeometry(QtCore.QRect(580, 50, 101, 41))
        self.nprocess_label.setObjectName("nprocess_label")
        self.type_reduction = QtWidgets.QComboBox(self.reduction_tab)
        self.type_reduction.setGeometry(QtCore.QRect(40, 80, 171, 25))
        self.type_reduction.setObjectName("type_reduction")
        self.type_reduction.addItem("")
        self.type_reduction.addItem("")
        self.type_reduciton_label = QtWidgets.QLabel(self.reduction_tab)
        self.type_reduciton_label.setGeometry(QtCore.QRect(50, 50, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.type_reduciton_label.setFont(font)
        self.type_reduciton_label.setObjectName("type_reduciton_label")
        self.start_reduction = QtWidgets.QPushButton(self.reduction_tab)
        self.start_reduction.setGeometry(QtCore.QRect(50, 190, 141, 41))
        self.start_reduction.setObjectName("start_reduction")
        self.mean_reduction = QtWidgets.QRadioButton(self.reduction_tab)
        self.mean_reduction.setGeometry(QtCore.QRect(40, 110, 131, 23))
        self.mean_reduction.setObjectName("mean_reduction")
        self.median_reduction = QtWidgets.QRadioButton(self.reduction_tab)
        self.median_reduction.setGeometry(QtCore.QRect(40, 140, 131, 23))
        self.median_reduction.setChecked(True)
        self.median_reduction.setObjectName("median_reduction")
        self.readme_reduction = QtWidgets.QTextEdit(self.reduction_tab)
        self.readme_reduction.setGeometry(QtCore.QRect(20, 250, 711, 331))
        self.readme_reduction.setReadOnly(True)
        self.readme_reduction.setObjectName("readme_reduction")
        self.tabWdgt.addTab(self.reduction_tab, "")
        self.db_tab = QtWidgets.QWidget()
        self.db_tab.setObjectName("db_tab")
        self.db_connection = QtWidgets.QGroupBox(self.db_tab)
        self.db_connection.setGeometry(QtCore.QRect(10, 0, 741, 211))
        self.db_connection.setObjectName("db_connection")
        self.establish_connection = QtWidgets.QPushButton(self.db_connection)
        self.establish_connection.setGeometry(QtCore.QRect(210, 70, 171, 31))
        self.establish_connection.setObjectName("establish_connection")
        self.db_label = QtWidgets.QLabel(self.db_connection)
        self.db_label.setGeometry(QtCore.QRect(0, 30, 211, 31))
        self.db_label.setObjectName("db_label")
        self.disconnect = QtWidgets.QPushButton(self.db_connection)
        self.disconnect.setGeometry(QtCore.QRect(230, 100, 131, 31))
        self.disconnect.setObjectName("disconnect")
        self.db_editmode = QtWidgets.QCheckBox(self.db_connection)
        self.db_editmode.setEnabled(True)
        self.db_editmode.setGeometry(QtCore.QRect(240, 40, 141, 23))
        self.db_editmode.setObjectName("db_editmode")
        self.db_output = QtWidgets.QTextEdit(self.db_connection)
        self.db_output.setGeometry(QtCore.QRect(390, 10, 341, 171))
        self.db_output.setReadOnly(True)
        self.db_output.setObjectName("db_output")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.db_connection)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 191, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.db_form = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.db_form.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.db_form.setContentsMargins(0, 0, 0, 0)
        self.db_form.setSpacing(2)
        self.db_form.setObjectName("db_form")
        self.db_host = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_host.sizePolicy().hasHeightForWidth())
        self.db_host.setSizePolicy(sizePolicy)
        self.db_host.setEchoMode(QtWidgets.QLineEdit.Password)
        self.db_host.setObjectName("db_host")
        self.db_form.addWidget(self.db_host)
        self.db_username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_username.sizePolicy().hasHeightForWidth())
        self.db_username.setSizePolicy(sizePolicy)
        self.db_username.setObjectName("db_username")
        self.db_form.addWidget(self.db_username)
        self.db_password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_password.sizePolicy().hasHeightForWidth())
        self.db_password.setSizePolicy(sizePolicy)
        self.db_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.db_password.setObjectName("db_password")
        self.db_form.addWidget(self.db_password)
        self.db_query = QtWidgets.QGroupBox(self.db_tab)
        self.db_query.setGeometry(QtCore.QRect(0, 160, 751, 461))
        self.db_query.setObjectName("db_query")
        self.db_table = QtWidgets.QTableView(self.db_query)
        self.db_table.setGeometry(QtCore.QRect(0, 150, 745, 313))
        self.db_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.db_table.setSortingEnabled(False)
        self.db_table.setObjectName("db_table")
        self.formLayoutWidget = QtWidgets.QWidget(self.db_query)
        self.formLayoutWidget.setGeometry(QtCore.QRect(370, 40, 221, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.db_query_buttons = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.db_query_buttons.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.db_query_buttons.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.db_query_buttons.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.db_query_buttons.setFormAlignment(QtCore.Qt.AlignCenter)
        self.db_query_buttons.setContentsMargins(0, 0, 0, 0)
        self.db_query_buttons.setHorizontalSpacing(6)
        self.db_query_buttons.setVerticalSpacing(1)
        self.db_query_buttons.setObjectName("db_query_buttons")
        self.db_update = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_update.sizePolicy().hasHeightForWidth())
        self.db_update.setSizePolicy(sizePolicy)
        self.db_update.setObjectName("db_update")
        self.db_query_buttons.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_update)
        self.db_download = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_download.sizePolicy().hasHeightForWidth())
        self.db_download.setSizePolicy(sizePolicy)
        self.db_download.setObjectName("db_download")
        self.db_query_buttons.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_download)
        self.db_sendquery = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_sendquery.sizePolicy().hasHeightForWidth())
        self.db_sendquery.setSizePolicy(sizePolicy)
        self.db_sendquery.setObjectName("db_sendquery")
        self.db_query_buttons.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_sendquery)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.db_query)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 361, 111))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(4)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.db_databases_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_databases_label.sizePolicy().hasHeightForWidth())
        self.db_databases_label.setSizePolicy(sizePolicy)
        self.db_databases_label.setObjectName("db_databases_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.db_databases_label)
        self.db_databases = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_databases.sizePolicy().hasHeightForWidth())
        self.db_databases.setSizePolicy(sizePolicy)
        self.db_databases.setObjectName("db_databases")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.db_databases)
        self.db_cols_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_cols_label.sizePolicy().hasHeightForWidth())
        self.db_cols_label.setSizePolicy(sizePolicy)
        self.db_cols_label.setAlignment(QtCore.Qt.AlignCenter)
        self.db_cols_label.setObjectName("db_cols_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.db_cols_label)
        self.db_where_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_where_label.sizePolicy().hasHeightForWidth())
        self.db_where_label.setSizePolicy(sizePolicy)
        self.db_where_label.setAlignment(QtCore.Qt.AlignCenter)
        self.db_where_label.setObjectName("db_where_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.db_where_label)
        self.db_cols = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_cols.sizePolicy().hasHeightForWidth())
        self.db_cols.setSizePolicy(sizePolicy)
        self.db_cols.setObjectName("db_cols")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_cols)
        self.db_where = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_where.sizePolicy().hasHeightForWidth())
        self.db_where.setSizePolicy(sizePolicy)
        self.db_where.setText("")
        self.db_where.setObjectName("db_where")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_where)
        self.db_tables_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_tables_label.sizePolicy().hasHeightForWidth())
        self.db_tables_label.setSizePolicy(sizePolicy)
        self.db_tables_label.setAlignment(QtCore.Qt.AlignCenter)
        self.db_tables_label.setObjectName("db_tables_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.db_tables_label)
        self.db_tables = QtWidgets.QComboBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_tables.sizePolicy().hasHeightForWidth())
        self.db_tables.setSizePolicy(sizePolicy)
        self.db_tables.setObjectName("db_tables")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_tables)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.db_query)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(620, 50, 101, 71))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.db_add_remove_form = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.db_add_remove_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.db_add_remove_form.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.db_add_remove_form.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.db_add_remove_form.setFormAlignment(QtCore.Qt.AlignCenter)
        self.db_add_remove_form.setContentsMargins(0, 0, 0, 0)
        self.db_add_remove_form.setHorizontalSpacing(6)
        self.db_add_remove_form.setVerticalSpacing(1)
        self.db_add_remove_form.setObjectName("db_add_remove_form")
        self.db_add = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_add.sizePolicy().hasHeightForWidth())
        self.db_add.setSizePolicy(sizePolicy)
        self.db_add.setObjectName("db_add")
        self.db_add_remove_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_add)
        self.db_delete = QtWidgets.QPushButton(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.db_delete.sizePolicy().hasHeightForWidth())
        self.db_delete.setSizePolicy(sizePolicy)
        self.db_delete.setObjectName("db_delete")
        self.db_add_remove_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_delete)
        self.tabWdgt.addTab(self.db_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWdgt.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDEN Utilities"))
        self.transfer_info.setTitle(_translate("MainWindow", "Information for Storage"))
        self.output.setToolTip(_translate("MainWindow", "<html><head/><body><p>Messages from the program</p></body></html>"))
        self.output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">OUTPUT</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Welcome to EDEN Utils.</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> </span></p></body></html>"))
        self.select_dir.setText(_translate("MainWindow", "Select Source Directory"))
        self.MS_dir.setText(_translate("MainWindow", "(Optional) Manual Storage directory"))
        self.text_dir.setPlaceholderText(_translate("MainWindow", "e.g: /home/user/user_folder"))
        self.Ms_text.setPlaceholderText(_translate("MainWindow", "e.g: /home/user/incompatibles"))
        self.ovr_transfer.setText(_translate("MainWindow", "Override destination"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.strt_trnsf.setText(_translate("MainWindow", "Start Transfer"))
        self.tabWdgt.setTabText(self.tabWdgt.indexOf(self.transfer_tab), _translate("MainWindow", "Transfer Data"))
        self.rname_box.setTitle(_translate("MainWindow", "Header Value Change"))
        item = self.table_rname.horizontalHeaderItem(0)
        item.setToolTip(_translate("MainWindow", "FIT key to be changed"))
        item = self.table_rname.horizontalHeaderItem(1)
        item.setToolTip(_translate("MainWindow", "string to set key value"))
        item = self.table_rname.horizontalHeaderItem(2)
        item.setToolTip(_translate("MainWindow", "base name of file"))
        __sortingEnabled = self.table_rname.isSortingEnabled()
        self.table_rname.setSortingEnabled(False)
        self.table_rname.setSortingEnabled(__sortingEnabled)
        self.info_value_hrdset.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Information for modification<br/>(Up to 5 simultaneuos changes)</p></body></html>"))
        self.hrd_src_dir.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Enter the directory holding files to be renamed</span></p></body></html>"))
        self.hrd_src_dir.setPlaceholderText(_translate("MainWindow", "e.g. /home/Data/files"))
        self.app_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p></body></html>"))
        self.modified_dir.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Preferred directory to store modified files</span></p></body></html>"))
        self.modified_dir.setPlaceholderText(_translate("MainWindow", "e.g. /home/data/modified_files"))
        self.rname_src.setText(_translate("MainWindow", "Select directory of files"))
        self.rname_dest.setText(_translate("MainWindow", "(Optional) Select New Destination"))
        self.strt_rnaming.setText(_translate("MainWindow", "Start "))
        self.options_box_rname.setTitle(_translate("MainWindow", "Options"))
        self.keep_orig_rname.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">This will keep the original files and use copy functions instead of move functions. The renamed files will be copied to a subfolder with name:\' renamed files \'(unless specified on the right) </span></p></body></html>"))
        self.keep_orig_rname.setText(_translate("MainWindow", "Keep orignal files"))
        self.recursive_rname.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">This will allow the program to search the file basenames in subfolders</span></p></body></html>"))
        self.recursive_rname.setText(_translate("MainWindow", "Recursive file search"))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the recursive limit for the file search recursion ( 1 = \'No recursion\'). If empty, it will recurse completely.</span></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter recursive limit"))
        self.hrd_chng_type.setText(_translate("MainWindow", "   FIT header keys"))
        self.rname_type.setText(_translate("MainWindow", "   File names"))
        self.top_label.setText(_translate("MainWindow", "What are you renaming/changing"))
        self.app_info_rnamelabel.setText(_translate("MainWindow", "App Information"))
        self.tabWdgt.setTabText(self.tabWdgt.indexOf(self.renaming_tab), _translate("MainWindow", "Mass rename/modify"))
        self.input_files_reduction.setTitle(_translate("MainWindow", "Input Files"))
        self.select_objs_reduction.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select all object FITS files to be reduced.</p></body></html>"))
        self.select_objs_reduction.setText(_translate("MainWindow", "Select Source of Object FITS"))
        self.select_cal_reduction.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select all calibrations FITS files to be used for the reduction.</p></body></html>"))
        self.select_cal_reduction.setText(_translate("MainWindow", "Select Dir. with Calibration FITS"))
        self.cal_comp.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Format:<br/>{Filter}, {BIN#}</span></p></body></html>"))
        self.cal_comp.setPlaceholderText(_translate("MainWindow", "\'Clear, 3 bin\' or  \'I, 2\'"))
        self.recycle_cal.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Check this if you want the program to try to find/reuse calibration files.<br/>If you this is unchecked, it will re-compute all files.</span></p></body></html>"))
        self.recycle_cal.setText(_translate("MainWindow", "Recycle Calibration files"))
        self.twilight_flats.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Check this if you want the program to use twilight flats.<br/>If this is unchecked, it will filter them out and try to use other flats.</span></p></body></html>"))
        self.twilight_flats.setText(_translate("MainWindow", "Use twilight flats"))
        self.nprocess.setToolTip(_translate("MainWindow", "Number of processes to split the work"))
        self.nprocess.setSpecialValueText(_translate("MainWindow", "Auto"))
        self.nprocess_label.setText(_translate("MainWindow", "Number of \n"
"Multiprocesses"))
        self.type_reduction.setItemText(0, _translate("MainWindow", "Full Calibration"))
        self.type_reduction.setItemText(1, _translate("MainWindow", "Only Calibration files"))
        self.type_reduciton_label.setText(_translate("MainWindow", "Type of Calibration"))
        self.start_reduction.setText(_translate("MainWindow", "Start Calibration"))
        self.mean_reduction.setText(_translate("MainWindow", "  Take Mean"))
        self.median_reduction.setText(_translate("MainWindow", "  Take Median"))
        self.readme_reduction.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">README</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">The Full Calibration</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> type is where selected raw object images and raw calibration files are used. You must select object files, and folder of calibration files. The program will choose the appropriate calibration files. This outputs final object images and mean/median of calibration files.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Only Calibration files</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> Reduction type is simply to get the median/mean of the calibration files. You must select folder with calibration files, and type in the text box the filter and binning for which to do this. Make sure that the files have the correct filter header info.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Checkout the options on the side for different combinations. For the reuse of calibration files, the program may not be able to find already-computed calibration files, so it will re-compute them with overwriting capability.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">OUTPUT:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p></body></html>"))
        self.tabWdgt.setTabText(self.tabWdgt.indexOf(self.reduction_tab), _translate("MainWindow", "Data Calibration"))
        self.db_connection.setTitle(_translate("MainWindow", "Connection"))
        self.establish_connection.setText(_translate("MainWindow", "Establish Connection"))
        self.db_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Only use this if you know what you\'re doing</p></body></html>"))
        self.db_label.setText(_translate("MainWindow", "Override MySQL info"))
        self.disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.db_editmode.setText(_translate("MainWindow", "Edit Mode"))
        self.db_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">This is program is a simple interface to the MySQL EDEN Database. Quick Startup:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">-This message box will serve as a notification box.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">-Default connection is to apaidani_general@distantearths.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">-Once connection has been established. The databases/tables drop-down list will fill up with available databases/tables. Once you select one you can make queries and download data as you please.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">-Please make sure columns are typed written exactly. Also, the conditions must be MySQL compatible; eg: AND,OR,&gt;,&lt;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">-Downloaded data is available in the following directory:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-style:italic;\"> ~/eden-utils/csv_data</span></p></body></html>"))
        self.db_host.setPlaceholderText(_translate("MainWindow", "Host"))
        self.db_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.db_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.db_query.setTitle(_translate("MainWindow", "Query"))
        self.db_update.setText(_translate("MainWindow", "Update"))
        self.db_download.setText(_translate("MainWindow", "Download as CSV file"))
        self.db_sendquery.setText(_translate("MainWindow", "SEND QUERY"))
        self.db_databases_label.setText(_translate("MainWindow", "Select Database"))
        self.db_cols_label.setText(_translate("MainWindow", "Columns "))
        self.db_where_label.setText(_translate("MainWindow", "Conditions"))
        self.db_cols.setToolTip(_translate("MainWindow", "<html><head/><body><p>Insert the columns to query from the selected database. Leave blank if you want to select all columns.</p></body></html>"))
        self.db_cols.setPlaceholderText(_translate("MainWindow", "Filname,`RA ss`, directory"))
        self.db_where.setToolTip(_translate("MainWindow", "<html><head/><body><p>Insert conditions to query filtered data from the selected database.</p></body></html>"))
        self.db_where.setPlaceholderText(_translate("MainWindow", "\' ID > 20\' AND `RA ss` > 12"))
        self.db_tables_label.setText(_translate("MainWindow", "Tables"))
        self.db_add.setText(_translate("MainWindow", "Add Row"))
        self.db_delete.setText(_translate("MainWindow", "Delete Row"))
        self.tabWdgt.setTabText(self.tabWdgt.indexOf(self.db_tab), _translate("MainWindow", "Database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

